### ISSUE TITLE
Crashing due to obfuscation with proguard

### ISSUE THREAD

**Issue by omkarhande** [box/box-android-preview-sdk#26]
What all packages are to be omitted for obfuscation by Proguard?
Right now I have added the following, but it is still crashing on accessing PDFs

`
-keep class com.pspdfkit.** { *; }
-keep class com.box.** { *; }
`

**Comment by lupajz** [comment]
Hello @omkarhande. Could you please fill out the report in [this format](https://github.com/box/box-android-preview-sdk/blob/master/ISSUE_TEMPLATE.md) so we would have at least some information ?
